# Lesson 7: Creating itineraries for multiple cities

In this lesson, you will use everything you have seen so far to plan the perfect vacation around the world!

To get started, import some helper functions:

In [1]:
from helper_functions import print_llm_response, get_llm_response, display_table
from IPython.display import Markdown
import csv

## Reading travel itineraries from a CSV file

First, define a new function that reads data stored in a CSV file and returns it as a dictionary variable:

In [2]:
def read_csv(file):
    f = open(file, "r")
    
    csv_reader = csv.DictReader(f)
    data = []
    for row in csv_reader:
        data.append(row)
    f.close()
    
    return data

Next, load itineraries from `itinerary.csv` using the function you just defined (notice how much less code this is!) and then display the table of itineraries:

In [3]:
# Read the itinerary.csv file
itinerary = read_csv("itinerary.csv")

# Display the itinerary
display_table(itinerary)

## Reading restaurant information from food journal entries

Now create a new function called `read_journal` that reads in the contents of a plain text file with '.txt' extension and stores it into a string variable:

In [4]:
# The function called 'read_journal'
def read_journal(journal_file):
    f = open(journal_file, "r")
    journal = f.read() 
    f.close()

    # Return the journal content
    return journal

Note that you used this function in an earlier lesson - now you know how it works!

You can now use the `read_journal` function to read in a food journal file - let's start with Sydney:

In [5]:
journal = read_journal("sydney.txt")

print(journal)

My culinary adventure began at Saint Peter, a renowned seafood restaurant in Paddington. This place is a temple to Australian seafood, and the "Murray Cod" was a revelation. The fish, sourced from the Murray River, was perfectly cooked, with a crispy skin and tender, flaky flesh. It was served with a simple yet flavorful accompaniment of seasonal vegetables, allowing the quality of the fish to shine. The restaurant's dedication to sustainability and nose-to-tail seafood cooking added an educational aspect to the delicious meal.

Next, I visited Billy Kwong in Potts Point, where celebrated chef Kylie Kwong puts a unique spin on modern Australian cuisine using native ingredients. The standout dish here was the "Crispy Skin Duck with Davidson’s Plum Sauce." The duck was cooked to perfection, with a rich, flavorful meat and delightfully crispy skin, complemented by the tart and slightly sweet Davidson’s plum sauce. This dish was a perfect example of how traditional recipes can be elevated with local, indigenous ingredients, creating something both familiar and new.

In search of a true Australian pub experience, I headed to The Lord Nelson Brewery Hotel in The Rocks. This historic pub serves up hearty, classic Australian fare, and the "Roast Lamb" was exactly what I was craving. The lamb, roasted to tender perfection, was served with a medley of root vegetables and a rich gravy, making for a comforting and satisfying meal. Paired with one of their house-brewed ales, it was a quintessential Aussie pub experience that I would highly recommend.

I couldn't miss out on trying some of the famous Australian barbecue, so I headed to Vic's Meat Market at the Sydney Fish Market. The "BBQ Beef Brisket" was a highlight, slow-cooked to achieve a melt-in-the-mouth texture, and served with a tangy barbecue sauce. The smoky, rich flavor of the brisket was enhanced by the vibrant, outdoor setting of the market, where the aroma of grilling meat filled the air.

To round off my exploration of local cuisine, I visited Bennelong, located within the iconic Sydney Opera House. This fine dining restaurant celebrates Australian produce in every dish. The "Sydney Rock Oysters" were an exquisite start to the meal, served with a delicate vinaigrette that highlighted their briny freshness. The oysters, sourced from local waters, were plump and succulent, offering a pure taste of the sea.

Write a prompt that extracts restaurant and specialty dish information from the journal text and stores it in CSV format:

In [6]:
# Write the prompt
prompt = f"""Please extract a comprehensive list of the restaurants 
and their respective specialties mentioned in the following journal entry. 
Ensure that each restaurant name is accurately identified and listed. 
Provide your answer in CSV format, ready to save. 
Exclude the "```csv" declaration, don't add spaces after the comma, include column headers.

Format:
Restaurant, Specialty
Res_1, Sp_1
...

Journal entry:
{journal}
"""

# Print the prompt
print_llm_response(prompt)

Restaurant,Specialty
Saint Peter,Murray Cod
Billy Kwong,Crispy Skin Duck with Davidson’s Plum Sauce
The Lord Nelson Brewery Hotel,Roast Lamb
Vic's Meat Market,BBQ Beef Brisket
Bennelong,Sydney Rock Oysters

Read in restaurant information from `Sydney.csv` file that was created for you and display it using the `display_table` function:

In [7]:
# Use the read_csv function
sydney_restaurants = read_csv("Sydney.csv")

display_table(sydney_restaurants)

## Creating detailed itineraries with restaurant suggestions

In this section, you'll combine the data in the journal and the itinerary to create a detailed plan for your visit to Sydney. 

To access Sydney's data in the ```itinerary``` list, you have to use index '6' since Sydney is the seventh trip destination.

In [8]:
# Select Sydney from the 'itinerary' list
trip_stop = itinerary[6]

Next, store all the information from that ```trip_stop```, as well as the restaurant information you read in above, in separate variables:

In [9]:
city = trip_stop["City"]
country = trip_stop["Country"]
arrival = trip_stop["Arrival"]
departure = trip_stop["Departure"]
restaurants = sydney_restaurants

Pass all of this information in a detailed prompt to an LLM to create a detailed itinerary:

In [10]:
# Write the prompt
prompt = f"""I will visit {city}, {country} from {arrival} to {departure}. 
Create a daily itinerary with detailed activities. 
Designate times for breakfast, lunch, and dinner. 

I want to visit the restaurants listed in the restaurant dictionary 
without repeating any place. Make sure to mention the specialty
that I should try at each of them.

Restaurant dictionary:
{restaurants}

"""

response = get_llm_response(prompt)

# Print the LLM response in Markdown format
display(Markdown(response))

**Sydney Itinerary: August 18 - August 25**

---

**August 18 (Sunday)**
- Breakfast: 8:00 AM - Explore a local café near your accommodation
- Morning: 9:30 AM - Sydney Opera House tour
- Lunch: 12:30 PM - Carriageworks Farmers Market
  - Try: Kangaroo Pie
- Afternoon: 2:00 PM - Walk through the Royal Botanic Garden
- Dinner: 7:00 PM - The Lord Nelson Brewery Hotel
  - Try: Roast Lamb

---

**August 19 (Monday)**
- Breakfast: 8:00 AM - Local café or hotel
- Morning: 9:30 AM - Visit Taronga Zoo
- Lunch: 1:00 PM - Picnic at Balmoral Beach
- Afternoon: 3:00 PM - Manly Beach walk
- Dinner: 7:30 PM - Saint Peter
  - Try: Murray Cod

---

**August 20 (Tuesday)**
- Breakfast: 8:00 AM - Local café
- Morning: 9:30 AM - Explore The Rocks historic area
- Lunch: 12:30 PM - Bennelong (inside Sydney Opera House)
  - Try: Sydney Rock Oysters
- Afternoon: 2:30 PM - Museum of Contemporary Art
- Dinner: 7:00 PM - Casual dining or light meal near hotel

---

**August 21 (Wednesday)**
- Breakfast: 8:00 AM - Local café
- Morning: 9:30 AM - Blue Mountains day trip
- Lunch: 12:30 PM - At a café in Blue Mountains (not from list)
- Afternoon: Continue Blue Mountains exploration
- Dinner: 7:30 PM - Vic's Meat Market
  - Try: BBQ Beef Brisket

---

**August 22 (Thursday)**
- Breakfast: 8:00 AM - Local café
- Morning: 9:30 AM - Sydney Harbour Bridge climb or walk
- Lunch: 12:30 PM - Explore Circular Quay food options
- Afternoon: 2:00 PM - Art Gallery of NSW
- Dinner: 7:00 PM - Billy Kwong
  - Try: Crispy Skin Duck with Davidson’s Plum Sauce

---

**August 23 (Friday)**
- Breakfast: 8:00 AM - Local café
- Morning: 9:30 AM - Bondi to Coogee coastal walk
- Lunch: 1:00 PM - Bondi Beach café
- Afternoon: Relax at Bondi Beach or visit local shops
- Dinner: 7:00 PM - Choose a new local restaurant (not from list)

---

**August 24 (Saturday)**
- Breakfast: 8:00 AM - Local café
- Morning: 9:30 AM - Visit Sydney Aquarium and Wildlife Sydney Zoo
- Lunch: 12:30 PM - Darling Harbour eateries
- Afternoon: Shopping at Queen Victoria Building
- Dinner: 7:00 PM - Explore a new cuisine or revisit favorite spot

---

**August 25 (Sunday)**
- Breakfast: 8:00 AM - Local café
- Morning: 9:30 AM - Relax at your hotel or nearby park
- Lunch: 12:30 PM - Light meal at airport or nearby
- Departure

---

All listed restaurants are visited once with their specialties highlighted. Enjoy your trip!

## Create detailed itineraries for all the cities in your trip

You'll use a 'for' loop to iterate over all the cities in the ```itinerary``` list and create a detailed itinerary for each location:

In [15]:
# Create an empty dictionary to store the itinerary for each destination
detailed_itinerary = {}

 # Use the 'for' loop over the 'itinerary' list   
for trip_stop in itinerary:
    city = trip_stop["City"]
    country = trip_stop["Country"]
    arrival = trip_stop["Arrival"]
    departure = trip_stop["Departure"]

    rest_dict = read_csv(f"{city}.csv")
    
    print(f"Creating detailed itinerary for {city}, {country}.")
    
    prompt = f"""I will visit {city}, {country} from {arrival} to {departure}. 
    Create a daily itinerary with detailed activities. 
    Designate times for breakfast, lunch, and dinner. 

    I want to visit the restaurants listed in the restaurant dictionary without repeating any place.
    Make sure to mention the specialty that I should try at each of them.
    
    Make sure itinerary should comply with my waking up and get to bed timings. I wake up at 5:00AM and get to bed around 10:00PM.
    
    I'll visit the country with my wife so definitely will do sex. Please include this also.

    Restaurant dictionary:
    {rest_dict}

    """
    # Store the detailed itinerary for the city to the dictionary
    detailed_itinerary[city] = get_llm_response(prompt)

Creating detailed itinerary for New York, USA.
Creating detailed itinerary for Rio de Janeiro, Brazil.
Creating detailed itinerary for Cape Town, South Africa.
Creating detailed itinerary for Istanbul, Turkey.
Creating detailed itinerary for Paris, France.
Creating detailed itinerary for Tokyo, Japan.
Creating detailed itinerary for Sydney, Australia.

You can now access the detailed itinerary for any city by passing in the city name as the key to the `detailed_itinerary` dictionary:

In [17]:
# Print in Markdown format
display(Markdown(detailed_itinerary["New York"]))

Here is your detailed daily itinerary for New York from July 1 to July 8, including meals at the specified restaurants, sightseeing, and personal time. Wake-up is at 5:00 AM and bedtime around 10:00 PM.

---

**July 1 (Monday)**
- 5:00 AM: Wake up
- 6:00 AM: Breakfast at hotel or nearby cafe
- 7:00 AM - 12:00 PM: Visit Central Park (walk, boat ride, visit the Conservatory Garden)
- 12:30 PM: Lunch at Katz's Delicatessen - Try the Pastrami on rye
- 2:00 PM - 5:00 PM: Explore Lower East Side and Tenement Museum
- 6:00 PM: Dinner at Chelsea Market (Lobster Place) - Try the Lobster rolls
- 8:00 PM - 9:30 PM: Personal time with your wife
- 10:00 PM: Bedtime

---

**July 2 (Tuesday)**
- 5:00 AM: Wake up
- 6:00 AM: Breakfast at hotel
- 7:00 AM - 12:00 PM: Visit the Statue of Liberty and Ellis Island
- 12:30 PM: Lunch at Gramercy Tavern - Try the Roasted chicken with seasonal vegetables
- 2:00 PM - 5:00 PM: Walk the High Line and visit Chelsea art galleries
- 6:30 PM: Dinner at Peter Luger Steak House - Try the Porterhouse steak
- 8:30 PM - 9:30 PM: Personal time with your wife
- 10:00 PM: Bedtime

---

**July 3 (Wednesday)**
- 5:00 AM: Wake up
- 6:00 AM: Breakfast at hotel
- 7:00 AM - 12:00 PM: Visit the Metropolitan Museum of Art
- 12:30 PM: Lunch at a local cafe (light meal)
- 2:00 PM - 5:00 PM: Explore Fifth Avenue shopping and Rockefeller Center
- 6:00 PM: Dinner at Eleven Madison Park - Try the Sunflower seed risotto
- 8:00 PM - 9:30 PM: Personal time with your wife
- 10:00 PM: Bedtime

---

**July 4 (Thursday)**
- 5:00 AM: Wake up
- 6:00 AM: Breakfast at hotel
- 7:00 AM - 12:00 PM: Visit the 9/11 Memorial & Museum and One World Observatory
- 12:30 PM: Lunch at a nearby deli or cafe
- 2:00 PM - 5:00 PM: Walk across Brooklyn Bridge and explore DUMBO
- 6:00 PM: Dinner at a local restaurant of your choice (try New York-style pizza)
- 8:00 PM - 9:30 PM: Personal time with your wife
- 10:00 PM: Bedtime

---

**July 5 (Friday)**
- 5:00 AM: Wake up
- 6:00 AM: Breakfast at hotel
- 7:00 AM - 12:00 PM: Visit MoMA and nearby Bryant Park
- 12:30 PM: Lunch at a local cafe
- 2:00 PM - 5:00 PM: Explore Times Square and Broadway area
- 6:00 PM: Dinner at a rooftop restaurant with city views
- 8:00 PM - 9:30 PM: Personal time with your wife
- 10:00 PM: Bedtime

---

**July 6 (Saturday)**
- 5:00 AM: Wake up
- 6:00 AM: Breakfast at hotel
- 7:00 AM - 12:00 PM: Visit the American Museum of Natural History
- 12:30 PM: Lunch at a local cafe
- 2:00 PM - 5:00 PM: Walk through Greenwich Village and Washington Square Park
- 6:00 PM: Dinner at a jazz club with dinner service
- 8:00 PM - 9:30 PM: Personal time with your wife
- 10:00 PM: Bedtime

---

**July 7 (Sunday)**
- 5:00 AM: Wake up
- 6:00 AM: Breakfast at hotel
- 7:00 AM - 12:00 PM: Visit the New York Botanical Garden or Bronx Zoo
- 12:30 PM: Lunch at a local cafe
- 2:00 PM - 5:00 PM: Relax or shopping in SoHo
- 6:00 PM: Dinner at a fine dining restaurant of your choice
- 8:00 PM - 9:30 PM: Personal time with your wife
- 10:00 PM: Bedtime

---

**July 8 (Monday)**
- 5:00 AM: Wake up
- 6:00 AM: Breakfast at hotel
- 7:00 AM - 10:00 AM: Last-minute sightseeing or shopping
- 10:30 AM: Check out and depart

---

Enjoy your trip and time with your wife!

## Try it yourself! 

Update the code below to check out the itinerary for another city. 

**Options:**
- Cape Town
- Istanbul
- New York
- Paris
- Rio de Janeiro
- Sydney
- Tokyo

In [20]:
# Update the next line of code to view a different city
display(Markdown(detailed_itinerary["Istanbul"]))

Here is your detailed daily itinerary for Istanbul from July 25 to August 1, including meals at the specified restaurants and time for intimacy with your wife. You wake at 5:00 AM and sleep by 10:00 PM.

---

**July 25 (Thursday)**
- 5:00 AM: Wake up, morning routine
- 6:00 AM: Breakfast at Istiklal Street – try Simit (Turkish sesame bagel)
- 7:00 AM: Walk and explore Istiklal Avenue, visit shops and historic sites
- 12:30 PM: Lunch at Çiya Sofrası – try Kuzu Tandir (slow-cooked lamb)
- 2:00 PM: Visit Kadıköy Market and Moda neighborhood
- 6:00 PM: Return to hotel, rest
- 7:30 PM: Dinner at Karaköy Lokantası – try Midye Dolma (stuffed mussels)
- 9:00 PM: Intimacy time with your wife
- 10:00 PM: Sleep

---

**July 26 (Friday)**
- 5:00 AM: Wake up
- 6:00 AM: Breakfast at hotel or local café (light Turkish breakfast)
- 7:00 AM: Visit Hagia Sophia and Blue Mosque
- 12:30 PM: Lunch at local spot (not from list)
- 2:00 PM: Explore Topkapi Palace
- 6:00 PM: Return to hotel, rest
- 7:30 PM: Dinner at Asitane – try Mutancana (historic Ottoman stew)
- 9:00 PM: Intimacy time
- 10:00 PM: Sleep

---

**July 27 (Saturday)**
- 5:00 AM: Wake up
- 6:00 AM: Breakfast at local café (try Turkish tea and pastries)
- 7:00 AM: Bosphorus cruise and sightseeing
- 12:30 PM: Lunch at local fish restaurant (not from list)
- 2:00 PM: Visit Dolmabahçe Palace
- 6:00 PM: Rest at hotel
- 7:30 PM: Dinner at Mikla – try Lamb Rump (modern Turkish cuisine)
- 9:00 PM: Intimacy time
- 10:00 PM: Sleep

---

**July 28 to August 1**
Use these days to explore other Istanbul attractions such as Grand Bazaar, Spice Market, Galata Tower, and Princes’ Islands. For meals, choose local favorites outside the listed restaurants to avoid repeats. Continue your daily routine with breakfast around 6:00 AM, lunch around 12:30 PM, dinner around 7:30 PM, and intimacy time around 9:00 PM before bed at 10:00 PM.

---

Enjoy your trip and time with your wife!

## Congratulations on completing this course! 🎉🎉🎉

Please go onto the fourth and final course of this sequence where you'll learn how to extend the capabilities of Python using code written by other programmers!